spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: coupon_routh
          uri: lb://teamall-coupon
          predicates:
            - Path=/coupon/coupoon/**